# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# File: .github/dependabot.yml
version: 2                    # Required top‑level key
updates:
  - package-ecosystem: "composer"    # Use Composer for PHP packages
    directory: "/"                   # Look for composer.json at repo root
    schedule:
      interval: "weekly"             # Check for updates every week
